[tox]
requires = tox >= 4.25.0
env_list = linting{posargs}, formatting, typing-py31{0-4}, clean, py31{0-4}{posargs}, combine
labels =
    pytest = py31{0-4}
    pytest-ci = py31{0-4}-ci

[testenv]
dependency_groups = test
runner = uv-venv-lock-runner
setenv =
   COVERAGE_FILE = .coverage.{py_dot_ver}
   COVERALLS_FLAG_NAME = {env:TOX_OS:{on_platform}}_python{py_dot_ver}
   COVERALLS_PARALLEL = true
passenv =
   GITHUB_*
   COVERALLS_*
   TOX_OS

[testenv:linting{,-ci}]
description = run ruff linter
dependency_groups = lint
commands =
   linting: ruff check
   linting-ci: ruff check --output-format=github
package = skip
labels =
   lint
   linting

[testenv:formatting]
description = run ruff formatter
dependency_groups = lint
commands = ruff format --check
package = skip
labels =
   format
   formatting

[testenv:typing-py31{0-4}]
description = run mypy type checker on python {py_dot_ver}
depends = linting{posargs}, formatting
dependency_groups = typing, test
commands = mypy --python-version {py_dot_ver}
package = skip
labels =
   mypy
   typing

[testenv:clean]
description = clean up coverage files
depends = linting{posargs}, formatting
commands = python -c "import glob, os; [os.remove(f) for f in glob.glob('.coverage.*')]"
package = skip

[testenv:py31{0-4}{,-ci}]
description = run pytest on python {py_dot_ver}
depends = clean
dependency_groups =
   test
   py310-ci, py311-ci, py312-ci, py313-ci: ci
commands =
   pytest
   py310-ci, py311-ci, py312-ci, py313-ci: - coveralls

[testenv:combine]
description = combine coverage files and generate the html/xml reports
depends = py3{10-13}{posargs}
setenv = COVERAGE_FILE = .coverage
commands =
   coverage combine
   coverage html
   coverage xml
package = skip
