name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'tycmd.py'

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v10
        with:
          enable-cache: true
          python-version: '3.10'
      - name: Install dependencies
        run: uv sync --group doc
      - name: Sphinx build
        run: uv run sphinx-build docs/source docs/build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/
          force_orphan: true
