name: PyPI
on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
      - name: Publish package distributions to PyPI
        run: |
          pdm build --config-setting="--python-tag=py3" --config-setting="--py-limited-api=none"
          pdm publish --no-build --repository testpypi