name: PyPI
on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  pypi-publish:
    name: Build release packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest, windows-latest]
    env:
      COMMON_BUILD_CONFIG: ${{ '--config-setting="--python-tag=py3" --config-setting="--py-limited-api=none"' }}
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - name: Build distribution packages
        run: pdm build ${{ COMMON_BUILD_CONFIG }}
      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: dist/*.whl
