name: CI
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  Quality:
    name: "ruff & mypy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/ruff-action@v4.1.0
        with:
          version-file: uv.lock
      - run: ruff check
      - run: ruff format --check
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - uses: ./.github/actions/ensure-tycmd
        with:
          cache-key-os: ubuntu-latest
          manylinux-image: quay.io/pypa/manylinux_2_28_x86_64
          build-in-container: 'true'
      - name: Sync dependencies
        run: uv sync --no-default-groups --group tox
      - run: uv run tox -m 'typing' --fail-fast -p --parallel-no-spinner

  Testing:
    needs: [Quality]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            manylinux-image: quay.io/pypa/manylinux_2_28_x86_64
          - os: ubuntu-24.04-arm
            manylinux-image: quay.io/pypa/manylinux_2_28_aarch64
          - os: macos-26-intel
          - os: macos-latest
          - os: windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v7
      - uses: ./.github/actions/ensure-tycmd
        with:
          cache-key-os: ${{ matrix.os }}
          manylinux-image: ${{ matrix.manylinux-image }}
          build-in-container: ${{ matrix.manylinux-image != '' }}
      - name: Sync dependencies
        run: uv sync --no-default-groups --group tox --group ci
      - name: Build wheel
        run: uv build --wheel
      - name: Run tox
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TOX_OS: ${{ matrix.os }}
        run: uv run tox --skip-env 'linting|formatting|typing' --installpkg dist/*.whl --fail-fast -p --parallel-no-spinner -- -ci

  Finish:
    needs: Testing
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: coverallsapp/github-action@v2
        continue-on-error: true
        with:
          parallel-finished: true
